[package]
name = "rust-programming-techniques"
version = "0.1.0"
authors = ["luke <luke@yorkbay.net.nz>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
